### ISSUE TITLE
Switch CI to using out custom JXcore build

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#25]
We only use SM on the devices so it's bad that we are using V8 in the VM.

**Comment by vjrantal** [comment]
Discussed offline that we are fine using V8 on desktop, but we need our custom build so that we can do PSK.

**Comment by vjrantal** [comment]
Here is what I did:

```
// Download and unzip http://jxcore.azureedge.net/jxcore/0312/release/jx_osx64v8.zip
$ cp <download-folder>/jx_osx64v8/jx $(which jx)
$ rm -rf ~/.jx/
```

Then I noticed that @cicorias has done a SpiderMonkey build even though the .zip package filename implies V8. This can be checked with:

```
$ jx -jsv
Mozilla SpiderMonkey v34
```

Because our desktop build doesn't currently work with SpiderMonkey, I couldn't complete this task today.

I'll continue after either of these two conditions is met:
1. A OS X build with V8 is release by @cicorias 
2. I am able to make the desktop build work with SpiderMonkey

**Comment by cicorias** [comment]
updated the CDN and initiated a purge. I verified jx -jsv is V8 after:

```
curl -o jx.zip http://jxcore.azureedge.net/jxcore/0312/release/jx_osx64v8.zip
unzip jx.zip
cicoriasmbp13@Shawns-MBP:~/Downloads/jx_osx64v8$ ./jx -jsv
Google V8 v3.14.5.9
```

**Comment by vjrantal** [comment]
This is now done and there is a success build after the update at https://github.com/thaliproject/Thali_CordovaPlugin/pull/673#issuecomment-200705817.
