### ISSUE TITLE
Entire project blocked on CI not behaving itself

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#47]
It looks like 742 doesn't cause CI to run when it is updated. We need to know why.

**Comment by czyzm** [comment]
It turned out that one of nodes was in some broken state and CI was not able to access it. This was blocking entire CI. Restarting the node seems to fix the issue... yes I know... 
![image](https://cloud.githubusercontent.com/assets/16643097/17137351/075bc246-533b-11e6-940a-af276c95a258.png)

Nevertheless, after that I did 3 test runs from BtLib repo and it worked fine.
