### ISSUE TITLE
Is CI able to output logging from Java?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#8]
In looking through the logs I don't see any logs from our Java code, only jxcore-log. If we are building as a release build then generally Android suppresses logs. Which is bad because we need to see those logs!

**Comment by obastemur** [comment]
Yes right. Let me know the identifier so I can add that to the filter.

**Comment by yaronyg** [comment]
@obastemur 
Question 1 - Are you sure that all Java log output from say "informational" and above is being published?
Question 2 - Are you intentionally filtering out everything but jx-core?

Using logcat can't we just release all the data that comes from the thalitest app?

**Comment by obastemur** [comment]
If we don't want to receive system related events, the best option is to put a filter. By default Android Log interface expects a tag parameter, for CI, it listens `thali-log` tag for anything Thali wants to log over Java, C++ etc. 

Updated CI with MainActivity + ActivityManager logs

**Comment by yaronyg** [comment]
Ville, please put your proposal together to send to Oguz on this issue.

**Comment by vjrantal** [comment]
@obastemur: I was about to do a proposal that matches to what I do locally, but when I checked the CI code, I realized it might require a change to the order the CI does things. I wanted to check from you if this change could cause some unwanted instabilities.

You can see from https://github.com/vjrantal/multi-device-helpers/blob/master/mstart#L25 roughly what I do locally, but this way requires that the app is started before logcat so that the process id can be queried. Based on a quick look at the code, the CI currently seems to wait for first logcat output before it starts the app (which makes sense).

What do you think - would it be a no-go to change to order so that app is first started and then logcat? We shouldn't lose any data by doing that way since we wouldn't run `logcat -c` in between so the logs from the beginning of the process should be in the buffer.

**Comment by obastemur** [comment]
`logcat -c` is not an option anymore. Everytime the test starts on a `restarted` phone.

**Comment by vjrantal** [comment]
@obastemur: Can you comment my question above?

I did notice that the phones gets restarted and a part of my proposal was that "we wouldn't run `logcat -c`".

**Comment by vjrantal** [comment]
We decided that to not lose any information, we get the logcat output without filters. Filtering can be done afterwards (e.g., grepping the file) when inspecting a particular log output.
